name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "21"
          cache: "gradle"
          cache-dependency-path: |
            android/gradle/wrapper/gradle-wrapper.properties
            android/build.gradle.kts
            android/app/build.gradle.kts

      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          flutter-version: "3.29.2"
          cache: true

      - run: flutter pub get
      - run: flutter test
      - run: flutter build apk --verbose
