name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          version: "3.29.2"
          cache: true
      - run: flutter pub get
      - run: flutter test
      - run: flutter build apk
